import { Calistoga, Inter, Manrope } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],

});

const calistoga = Calistoga({
  variable: "--font-calistoga",
  subsets: ["latin"],
  weight: ["400",]
});

export const metadata = {
  title: "Serenai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${calistoga.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
